In [50]:
import numpy as np # importing numpy (to install just !pip install numpy)

In [51]:
a=np.array([1,2,3,4,5,6]) # creating array in numpy
print(a)

[1 2 3 4 5 6]


In [52]:
b=np.array([[5,10,15,20],[35,40,45,50]]) # creating multi dimensional arrays
print(b)
c=np.array([1,2,3,4,5,6], dtype="int16") # change byte

[[ 5 10 15 20]
 [35 40 45 50]]


In [53]:
a.size  # gets number of elements

6

In [54]:
b.ndim # get dimension of array

2

In [55]:
b.shape # gets shape (rows, columns)

(2, 4)

In [56]:
a.dtype # gets datatype

dtype('int32')

In [57]:
# get total size
a.size *a .itemsize

24

In [58]:
c.itemsize

2

# accessing/changing specific elements, rows,columns etc

In [59]:
A=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(A)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [60]:
# Get specific element of an array
# array[row,column]
A[1,2] #A[1,-5]

10

In [61]:
# get specific row
A[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [62]:
# get specific column
A[:,3]

array([ 4, 11])

In [63]:
A[:,0:3:3] # ARRAY[row, start index:end index:skip by how much]

array([[1],
       [8]])

In [64]:
# change element of array

A[:,3]= 2
print(A)

[[ 1  2  3  2  5  6  7]
 [ 8  9 10  2 12 13 14]]


In [65]:
# changing element in another way
print("changing element in another way \n")
A[:,3]=A[:,1]+20 # replaces 4th elment in array(of every dimenson) to second element (of every dimension)
print(A)

print("changing elements so that they are different in each dimension\n")
# changing elements so that they are different in each dimension
A[:,1]=[1,2]
print(A)

changing element in another way 

[[ 1  2  3 22  5  6  7]
 [ 8  9 10 29 12 13 14]]
changing elements so that they are different in each dimension

[[ 1  1  3 22  5  6  7]
 [ 8  2 10 29 12 13 14]]


*accessing and changing elements of 3-dimen. arrays 

In [66]:
g=np.array([[[1,2],[7,8]],[[15,45], [4,5]]])

print(g)
print(g.ndim)
print(g.shape)

[[[ 1  2]
  [ 7  8]]

 [[15 45]
  [ 4  5]]]
3
(2, 2, 2)


In [67]:
# get specific element(s) in 3d arrays (work outside in)
g[0,1,1]
     

8

In [68]:
# replacing element
g[:,1,:] = [[9,9],[8,8]]


g[:,0,:] = [[7,8],[6,7]]
print(g)

[[[7 8]
  [9 9]]

 [[6 7]
  [8 8]]]


 ##### Initializing Different types of Arrays

In [69]:
# creates an array with tall elements being zero. u pass the number of zeros u want ie np,zero(3)
print(np.zeros([3]))
print(np.zeros([2,5]))


[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [70]:
hello=np.zeros([2,5,3])
hello.ndim

3

In [71]:
# creates an array with tall elements being ones. u pass the number of ones u want ie np,zero(3)
print(np.ones(6))
print(np.ones([3,4]))

[1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [72]:
# 3d array of ones
w=np.ones([1,3,1])
print(w)

[[[1.]
  [1.]
  [1.]]]


In [73]:
# same concept but with any number
np.full((3,4,2), 4.3)

array([[[4.3, 4.3],
        [4.3, 4.3],
        [4.3, 4.3],
        [4.3, 4.3]],

       [[4.3, 4.3],
        [4.3, 4.3],
        [4.3, 4.3],
        [4.3, 4.3]],

       [[4.3, 4.3],
        [4.3, 4.3],
        [4.3, 4.3],
        [4.3, 4.3]]])

In [74]:
# Any other number (full_like)
e=np.array([[1,2,4,5,6],[7,8,9,11,12]])
print(e.shape)
l=np.full_like(e, 2)
print(l)

(2, 5)
[[2 2 2 2 2]
 [2 2 2 2 2]]


In [75]:
# random decimal numbers
f=np.array([[3,4,5,6,7,8],[3,4,5,6,35,2]])
x=f.shape
s=np.random.rand(4,5)
v=np.random.random_sample(x)
print(f"{s}\n")
print(v)
# np.random.rand(f.shape)
# print(np.random.rand(f.shape))

[[0.07641857 0.77715072 0.90683601 0.90782482 0.62250013]
 [0.87076099 0.48972343 0.42880026 0.18604978 0.84011755]
 [0.74473836 0.03019017 0.84635467 0.72285399 0.42104791]
 [0.05039691 0.74930572 0.80906029 0.24819347 0.23366351]]

[[0.09356089 0.07210721 0.69980868 0.37146223 0.5240623  0.71847102]
 [0.86876587 0.07533855 0.15169654 0.88334466 0.71550235 0.18361871]]


In [76]:
# Random Integer Values
# ..................(min,max, size=(x,y))
np.random.randint(4,200, size=(3,3))

array([[163,  55,   9],
       [183,  67,  76],
       [ 27,   9, 140]])

In [77]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
# exercise make this matrix
# [[1. 1. 1. 1. 1.]
#  [1. 0. 0. 0. 1.]
#  [1. 0. 9. 0. 1.]
#  [1. 0. 0. 0. 1.]
#  [1. 1. 1. 1. 1.]]
output=np.ones((5,5))
inside=np.zeros((3,3))
inside[1,1]=(9)
print(output)
print(inside)
output[1:4, 1:4]=inside
print(output)
# print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [79]:
# note: be careful when copying arrays
a=np.array([2,4,6])
d=a
print(d)

# make change to array d
d[2]=12
print(d)
# it changes array "a" automatically when u change array "d"
print(a)

# to solve this issue we use the .copy() function like this
h = np.array([2,3,4,5])
j = h.copy()
j[0]=1
print(j)
print(h)

[2 4 6]
[ 2  4 12]
[ 2  4 12]
[1 3 4 5]
[2 3 4 5]


In [80]:
# mathematics with numpy
a=np.array([1,2,3,4,5])

# mutpiply
a*2

array([ 2,  4,  6,  8, 10])

In [81]:
# divison
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [82]:
# addition
a+2

array([3, 4, 5, 6, 7])

In [83]:
# subracting
a-2

array([-1,  0,  1,  2,  3])

In [84]:
# to the power
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [85]:
# cos ,sin,
print(np.cos(a))
print(np.sin(a))
print(np.tan(a))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [86]:
n=np.array([1,25,1,25,1])
a + n

array([ 2, 27,  4, 29,  6])

##### Linear Algebra

In [87]:
y=np.ones((4,3)) # .....ones((x,y))

b = np.full((3,5), 2) # .....full((y,2), 3)
# the column of one array should be same as row of other array

print(y)
print(b)
np.matmul(y,b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [88]:
# Statistics
stats=np.array([[0,4,8],[12,16,20]])
stats

array([[ 0,  4,  8],
       [12, 16, 20]])

In [89]:
# gets smallest number out of all elements in the array
np.min(stats)

0

In [90]:
# gets the largest number out of all elements in the array
np.max(stats)

20

In [91]:
# gets sum of all elements in the array
np.sum(stats)

60

In [92]:
# gets average nunber out of all elements in the array
np.mean(stats)

10.0

#### Reorganizing Arrays 

In [93]:
v = np.array([[3,6,9],[2,4,6]])
print(v)
t = v.reshape((3,1,2))
print(t)

[[3 6 9]
 [2 4 6]]
[[[3 6]]

 [[9 2]]

 [[4 6]]]


In [94]:
# Vertically stacking vectors
q = np.array([3,6,9,12])
u = np.array([2,4,6,8])
np.vstack([q,u])

f=np.array([[1,2,3,5,6],[7,8,9,10,11]])
y=f+2

print(f)
np.vstack([f,y])

[[ 1  2  3  5  6]
 [ 7  8  9 10 11]]


array([[ 1,  2,  3,  5,  6],
       [ 7,  8,  9, 10, 11],
       [ 3,  4,  5,  7,  8],
       [ 9, 10, 11, 12, 13]])

In [95]:
# Horizontal stack
i = np.ones((2,4))
k = np.zeros((2,2))
np.hstack((i,k))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### Load data from file

In [102]:
filedata=np.genfromtxt('data.txt', delimiter=',')
filedata=filedata.astype('int32')
print(filedata)

[  1   3   4   5   6   7   8   9   8   6   3  34  53   4  53  36 563   6
   6  63  36   6   6  46]


#### boolean masking and advanced indexing 

In [103]:
np.any([filedata > 30], axis=0)

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True, False,  True,  True,  True, False,
       False,  True,  True, False, False,  True])

In [104]:
# np.all([filedata > 20], axis=0)
np.all([filedata > 20], axis=1)

array([False])

In [105]:
((filedata>5) & (filedata<10))
# (~((filedata>5) & (filedata<10))) is opposite of  ((filedata>5) & (filedata<10))                         

array([False, False, False, False,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False,  True,
        True, False, False,  True,  True, False])

In [106]:
filedata>5

array([False, False, False, False,  True,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [107]:
filedata==3

array([False,  True, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [108]:
filedata[filedata > 5]

array([  6,   7,   8,   9,   8,   6,  34,  53,  53,  36, 563,   6,   6,
        63,  36,   6,   6,  46])

In [109]:
# indexing with lists
z=np.array([2,4,6,8,10])
z[[1,2,4]]

array([ 4,  6, 10])

In [110]:
# activity index the following matrix
# 1  2  3  4  5
# 6  7  8  9  10
# 11 12 13 14 15
# 16 17 18 19 20
# 21 22 23 24 25
# 26 27 28 29 30

#  a) get the numbers 11,12,16,17
#  b) get the numbers 2,8,14,20
#  c) get the numbers 4,5,24,25,29,30





####### solutions
# a) arrayvar[2:4,0:2]
# b) arrayvar[[0,1,2,3], [1,2,3,4]]
# c) a[[0,4,5], 3:]